# === שלב א': בונים את האפליקציה ===
FROM node:18-alpine AS builder

WORKDIR /app

# העתקת קבצי ניהול חבילות והתקנה
COPY package.json package-lock.json ./
RUN npm install

# --- התוספת שלנו מתחילה כאן ---
# קבלת המשתנה מתוך ה-docker-compose
ARG VITE_API_URL
# הפיכתו למשתנה סביבה ש-Vite יזהה בוודאות בזמן הבנייה
ENV VITE_API_URL=$VITE_API_URL
# --- התוספת שלנו מסתיימת כאן ---

# העתקת כל שאר הקוד והרצת פקודת הבנייה (מייצר את תיקיית dist)
COPY . .
RUN npm run build

# === שלב ב': מגישים את האפליקציה ===
FROM nginx:alpine
RUN sed -i '/application\/javascript/ s/js;/js mjs;/' /etc/nginx/mime.types
RUN echo "types { application/javascript mjs; }" > /etc/nginx/conf.d/mjs.conf

# העתקת התוצרים המוכנים משלב א' אל תוך התיקייה ש-Nginx מגיש ממנה
COPY --from=builder /app/dist /usr/share/nginx/html

RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d/

# השרת יאזין על פורט 80
EXPOSE 80

# פקודת ההרצה של Nginx
CMD ["nginx", "-g", "daemon off;"]