"""add_is_public_shared_at_to_documents

Revision ID: 7d17ad8b41b7
Revises: 83f375952ae6
Create Date: 2026-04-13 15:24:55.778891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d17ad8b41b7'
down_revision: Union[str, Sequence[str], None] = '83f375952ae6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('is_public', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('documents', sa.Column('shared_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'shared_at')
    op.drop_column('documents', 'is_public')
    # ### end Alembic commands ###
