"""add emoji column to threads

Revision ID: 9032b91fc2a1
Revises: b0bdf9f132a3
Create Date: 2026-03-02 15:08:06.918491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9032b91fc2a1'
down_revision: Union[str, Sequence[str], None] = 'b0bdf9f132a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('threads', sa.Column('emoji', sa.String(), nullable=True))
    op.create_foreign_key(None, 'threads', 'messages', ['forked_from_message_id'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'threads', type_='foreignkey')
    op.drop_column('threads', 'emoji')
    # ### end Alembic commands ###
