"""add_message_model_alias

Revision ID: a573eb3c552f
Revises: c94831423efe
Create Date: 2026-04-15 15:29:58.529614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a573eb3c552f'
down_revision: Union[str, Sequence[str], None] = 'c94831423efe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('model_alias', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'model_alias')
    # ### end Alembic commands ###
