"""grand_vision_schema_fixed

Revision ID: c94831423efe
Revises: c7cc2d36d878
Create Date: 2026-04-14 19:04:38.318357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c94831423efe'
down_revision: Union[str, Sequence[str], None] = 'c7cc2d36d878'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lecture_videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('video_reference', sa.String(length=1024), nullable=False),
    sa.Column('total_duration', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lecture_videos_id'), 'lecture_videos', ['id'], unique=False)
    op.create_table('study_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('persona_id', sa.String(), nullable=True),
    sa.Column('active_thread_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_accessed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['active_thread_id'], ['threads.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_study_sessions_id'), 'study_sessions', ['id'], unique=False)
    op.create_table('video_sync_index',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('lecture_video_id', sa.Integer(), nullable=False),
    sa.Column('page_or_slide_num', sa.Integer(), nullable=False),
    sa.Column('start_time_sec', sa.Integer(), nullable=False),
    sa.Column('end_time_sec', sa.Integer(), nullable=False),
    sa.Column('topics_covered', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['lecture_video_id'], ['lecture_videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_sync_index_id'), 'video_sync_index', ['id'], unique=False)
    op.create_table('session_memories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('persona_id', sa.String(), nullable=False),
    sa.Column('compression_level', sa.Integer(), nullable=False),
    sa.Column('injected_memory_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['study_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_memories_id'), 'session_memories', ['id'], unique=False)
    op.alter_column('chunks', 'document_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('chunks', 'text',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('chunks', 'chunk_index',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('documents', sa.Column('content_hash', sa.String(length=64), nullable=True))
    op.add_column('documents', sa.Column('storage_url', sa.String(length=512), nullable=True))
    op.alter_column('documents', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('documents', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_documents_content_hash'), 'documents', ['content_hash'], unique=False)
    op.alter_column('messages', 'thread_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('messages', 'role',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('messages', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('page_summaries', 'document_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('page_summaries', 'page_number',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('page_summaries', 'summary',
               existing_type=sa.TEXT(),
               nullable=False)
    op.add_column('personas', sa.Column('author_id', sa.Integer(), nullable=True))
    op.add_column('personas', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('personas', sa.Column('persona_type', sa.Enum('global', 'community', 'personal', name='persona_type', native_enum=False), server_default='global', nullable=False))
    op.add_column('personas', sa.Column('system_prompt', sa.Text(), nullable=True))
    op.add_column('personas', sa.Column('word_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('personas', sa.Column('original_persona_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'personas', 'personas', ['original_persona_id'], ['id'])
    op.create_foreign_key(None, 'personas', 'users', ['author_id'], ['id'])
    op.add_column('users', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('users', 'is_active')
    op.drop_constraint(None, 'personas', type_='foreignkey')
    op.drop_constraint(None, 'personas', type_='foreignkey')
    op.drop_column('personas', 'original_persona_id')
    op.drop_column('personas', 'word_count')
    op.drop_column('personas', 'system_prompt')
    op.drop_column('personas', 'persona_type')
    op.drop_column('personas', 'description')
    op.drop_column('personas', 'author_id')
    op.alter_column('page_summaries', 'summary',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('page_summaries', 'page_number',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('page_summaries', 'document_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('messages', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('messages', 'role',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('messages', 'thread_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_documents_content_hash'), table_name='documents')
    op.alter_column('documents', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('documents', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('documents', 'storage_url')
    op.drop_column('documents', 'content_hash')
    op.alter_column('chunks', 'chunk_index',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('chunks', 'text',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('chunks', 'document_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_session_memories_id'), table_name='session_memories')
    op.drop_table('session_memories')
    op.drop_index(op.f('ix_video_sync_index_id'), table_name='video_sync_index')
    op.drop_table('video_sync_index')
    op.drop_index(op.f('ix_study_sessions_id'), table_name='study_sessions')
    op.drop_table('study_sessions')
    op.drop_index(op.f('ix_lecture_videos_id'), table_name='lecture_videos')
    op.drop_table('lecture_videos')
    # ### end Alembic commands ###
